<?php
/**
 * @file
 * spells.features.conditional_fields.inc
 */

/**
 * Implements hook_conditional_fields_default_fields().
 */
function spells_conditional_fields_default_fields() {
  $items = array();

  $items[] = array(
    'entity' => 'spell',
    'bundle' => 'spell',
    'dependent' => 'field_spell_component_consumed',
    'dependee' => 'field_spell_components',
    'options' => array(
      'state' => 'visible',
      'condition' => 'value',
      'grouping' => 'AND',
      'effect' => 'show',
      'effect_options' => array(),
      'element_view' => array(
        1 => 1,
        2 => 2,
        5 => 0,
        3 => 0,
        4 => 0,
      ),
      'element_view_per_role' => 0,
      'element_view_roles' => array(
        1 => array(
          1 => 1,
          2 => 2,
          5 => 0,
          3 => 0,
          4 => 0,
        ),
        2 => array(
          1 => 1,
          2 => 2,
          5 => 0,
          3 => 0,
          4 => 0,
        ),
      ),
      'element_edit' => array(
        1 => 1,
        3 => 0,
      ),
      'element_edit_per_role' => 0,
      'element_edit_roles' => array(
        1 => array(
          1 => 1,
          3 => 0,
        ),
        2 => array(
          1 => 1,
          3 => 0,
        ),
      ),
      'selector' => '',
      'values_set' => 1,
      'value_form' => array(
        'm' => 'm',
        'v' => NULL,
        's' => NULL,
      ),
      'value' => array(
        0 => array(
          'value' => 'm',
        ),
      ),
      'values' => array(),
    ),
  );

  $items[] = array(
    'entity' => 'spell',
    'bundle' => 'spell',
    'dependent' => 'field_spell_component_cost',
    'dependee' => 'field_spell_components',
    'options' => array(
      'state' => 'visible',
      'condition' => 'value',
      'grouping' => 'AND',
      'effect' => 'show',
      'effect_options' => array(),
      'element_view' => array(
        1 => 1,
        2 => 2,
        5 => 0,
        3 => 0,
        4 => 0,
      ),
      'element_view_per_role' => 0,
      'element_view_roles' => array(
        1 => array(
          1 => 1,
          2 => 2,
          5 => 0,
          3 => 0,
          4 => 0,
        ),
        2 => array(
          1 => 1,
          2 => 2,
          5 => 0,
          3 => 0,
          4 => 0,
        ),
      ),
      'element_edit' => array(
        1 => 1,
        3 => 0,
      ),
      'element_edit_per_role' => 0,
      'element_edit_roles' => array(
        1 => array(
          1 => 1,
          3 => 0,
        ),
        2 => array(
          1 => 1,
          3 => 0,
        ),
      ),
      'selector' => '',
      'values_set' => 1,
      'value_form' => array(
        'm' => 'm',
        'v' => NULL,
        's' => NULL,
      ),
      'value' => array(
        0 => array(
          'value' => 'm',
        ),
      ),
      'values' => array(),
    ),
  );

  return $items;
}
