<?php

/**
 * Implements hook_menu().
 */
function dd5_menu() {

  $items['admin/dnd5'] = array(
    'title' => 'D&D 5e',
    'description' => 'Administer D&D 5.',
    'page callback' => 'dd5_admin_config_page',
    'access arguments' => array('access dd5 administration pages'),
    'file' => 'dd5.admin.inc',
  );

  return $items;
}

function dd5_entity_access($op, $entity = NULL) {
  return TRUE;
}

function dd5_entity_type_page($form, &$form_state, $entityType) {
  $controller = entity_ui_controller($entityType);
  return $controller->typeOverviewForm($form, $form_state);
}

function dd5_entity_add_page($entity_type) {
  $controller = entity_ui_controller($entity_type);
  return $controller->addPage();
}

function dd5_theme() {
  return array(
    'dd5_entity_add_list' => array(
      'variables' => array('content' => array()),
    ),
  );
}

/**
 * Displays the list of available model types for model creation.
 *
 * @ingroup themeable
 */
function theme_dd5_entity_add_list($variables) {
  $content = $variables['content'];
  $output = '';
  if ($content) {
    $output = '<dl class="type-list">';
    foreach ($content as $item) {
      $output .= '<dt>' . l($item['title'], $item['href']) . '</dt>';
      $output .= '<dd>' . filter_xss_admin($item['description']) . '</dd>';
    }
    $output .= '</dl>';
  }
  else {
    if (user_access('administer dd5 types')) {
      $output = '<p>' . t('Entities cannot be added because you have not created any types yet. Go to the type creation page to add a new type.') . '</p>';
    }
    else {
      $output = '<p>' . t('No types have been created yet for you to use.') . '</p>';
    }
  }

  return $output;
}